@startuml
class DisabilityExpertRegistrationController {
    + DisabilityExpertRegistrationController(disabilityExpertManager:UserManager<DisabilityExpert>, userResolveService:UserResolveService)
    + <<async>> RegisterDisabilityExpert(disabilityExpertRegistrationModel:DisabilityExpertRegistrationModel) : Task<IActionResult>
}
ControllerBase <|-- DisabilityExpertRegistrationController
@enduml
