@startuml
!include .\\.\webapi\Program.puml
!include .\\.\webapi\Controllers\HomeController.puml
!include .\\.\webapi\Services\AuthTokenService.puml
!include .\\.\webapi\Services\IdbContextFactory.puml
!include .\\.\webapi\Services\UserManagerWrapper.puml
!include .\\.\webapi\Services\UserResolveService.puml
!include .\\.\webapi\Controllers\authentication\LoginController.puml
!include .\\.\webapi\Controllers\authentication\LogoutController.puml
!include .\\.\webapi\Controllers\authentication\RefreshController.puml
!include .\\.\webapi\Data\Bases\IdentityBaseContext.puml
!include .\\.\webapi\Data\Users\CompanyResearchContext.puml
!include .\\.\webapi\Data\Users\DisabilityExpertGuardiansContext.puml
!include .\\.\webapi\Helpers\Enums\UserTypes.puml
!include .\\.\webapi\Helpers\Interfaces\IIdbContextFactory.puml
!include .\\.\webapi\Helpers\Interfaces\IUserManagerWrapper.puml
!include .\\.\webapi\Migrations\company\20231130150051_InitialCompany.puml
!include .\\.\webapi\Migrations\company\20231130150051_InitialCompany.Designer.puml
!include .\\.\webapi\Migrations\company\20231130151238_APiKey.puml
!include .\\.\webapi\Migrations\company\20231130151238_APiKey.Designer.puml
!include .\\.\webapi\Migrations\company\20231202155117_CompanyChangedRefreshTokenLocation.puml
!include .\\.\webapi\Migrations\company\20231202155117_CompanyChangedRefreshTokenLocation.Designer.puml
!include .\\.\webapi\Migrations\company\CompanyResearchContextModelSnapshot.puml
!include .\\.\webapi\Models\Accounts\Company.puml
!include .\\.\webapi\Models\Accounts\DisabilityExpert.puml
!include .\\.\webapi\Models\Accounts\Guardian.puml
!include .\\.\webapi\Models\Accounts\HumanBase.puml
!include .\\.\webapi\Models\Accounts\UserBase.puml
!include .\\.\webapi\Models\Disabilities\Disibility.puml
!include .\\.\webapi\Controllers\authentication\registration\CompanyRegistrationController.puml
!include .\\.\webapi\Controllers\authentication\registration\DisabilityExpertRegistrationController.puml
!include .\\.\webapi\Models\Authentication\Login\AuthResponseModel.puml
!include .\\.\webapi\Models\Authentication\Login\LoginModel.puml
!include .\\.\webapi\Models\Authentication\RefreshToken\NewRefreshTokenModel.puml
!include .\\.\webapi\Models\Authentication\RefreshToken\RefreshBearerTokenModel.puml
!include .\\.\webapi\Models\Authentication\RefreshToken\RefreshToken.puml
!include .\\.\webapi\Models\Authentication\Register\CompanyRegistrationModel.puml
!include .\\.\webapi\Models\Authentication\Register\DisabilityExpertRegistrationModel.puml
!include .\\.\webapi\Models\Authentication\Register\RegisterModelBase.puml
!include .\\.\webapi\obj\Debug\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\.\webapi\obj\Debug\net7.0\webapi.AssemblyInfo.puml
!include .\\.\webapi\obj\Debug\net7.0\webapi.GlobalUsings.g.puml
!include .\\.\webapi\obj\Debug\net7.0\webapi.MvcApplicationPartsAssemblyInfo.puml
!include .\\.\webapi\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\.\webapi\obj\Debug\net8.0\webapi.AssemblyInfo.puml
!include .\\.\webapi\obj\Debug\net8.0\webapi.GlobalUsings.g.puml
!include .\\.\webapi\obj\Debug\net8.0\webapi.MvcApplicationPartsAssemblyInfo.puml
!include .\\.\webapi\obj\Release\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\.\webapi\obj\Release\net7.0\webapi.AssemblyInfo.puml
!include .\\.\webapi\obj\Release\net7.0\webapi.GlobalUsings.g.puml
!include .\\.\webapi\obj\Release\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\.\webapi\obj\Release\net8.0\webapi.AssemblyInfo.puml
!include .\\.\webapi\obj\Release\net8.0\webapi.GlobalUsings.g.puml
@enduml
